### ISSUE TITLE
Improvement proposition: using Terraform remote state with GCS bucket instead of local state.

### ISSUE THREAD

**Issue by aurelienlegrand** [GoogleCloudPlatform/gke-anthos-holistic-demo#3]
As discussed, I think it would be better to use Terraform remote state with a GCS bucket in this demo to showcase Terraform best practices instead of using local state.
We could add an init script that would create the GCS bucket if needed.

**Comment by chrislovecnm** [comment]
Thanks! I am going to close this and open it in the https://github.com/GoogleCloudPlatform/gke-terraform-generator project!
